### ISSUE TITLE
Do not run __init__ scripts and notebooks

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoBuild#12]
These are both being run on the build server, doesnt cause problems but is extra noise.

**Comment by Jammy2211** [comment]
There are also some README.rst files being run:

https://github.com/Jammy2211/PyAutoBuild/actions/runs/3554771364/jobs/5971084977

**Comment by rhayes777** [comment]
lol

**Comment by Jammy2211** [comment]
Still happening https://github.com/Jammy2211/PyAutoBuild/actions/runs/3603725018/jobs/6072317788
