### ISSUE TITLE
Caching run_python.py and run.py scripts

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoBuild#4]
Currently, I run `run_python.py` and if it breaks, I have to rerun every script in the workspace to get to the same point. 

Could you put some sort of caching in, so that a rerun always starts from where it last broke? (We could have a script `clean.py` to remove the cache for a from-scratch run).

**Comment by rhayes777** [comment]
One issue is that some scripts depend on the output of other scripts. We might be able to do each directory in the workspace in parallel so things run faster. We could also potentially skip phases in the build using commands in the git commit but I think that might be risky.
